SEED_USE_CASES = [
    {
        "domain": "Finance",
        "subdomain": "Risk & Compliance",
        "use_case_name": "Credit Card Fraud Detection",
        "description": "The model learns normal spending patterns from historical transactions. New transactions are scored in milliseconds; if the anomaly score crosses a threshold, the transaction is flagged for review or blocked.",
        "ml_technique": "Isolation Forest + Logistic Regression",
        "input_data": "Transaction history, amount, location, time",
        "value": "Reduces false positives and detects fraudulent transactions in real-time.",
        "futuristic_view": "Federated learning across banks without sharing raw data, plus GNNs to catch collusive fraud rings.",
        "client_ready_details": "Deployed as a REST API with model drift monitoring (Evidently AI), explained via SHAP values.",
        "keyword": "fraud detection"
    },
    {
        "domain": "Finance",
        "subdomain": "Lending",
        "use_case_name": "Alternative Credit Scoring",
        "description": "Evaluates creditworthiness of individuals lacking traditional credit history by analyzing alternative data sources.",
        "ml_technique": "Gradient Boosting (XGBoost/LightGBM)",
        "input_data": "Utility bills, mobile phone usage, rental payments",
        "value": "Expands customer base while maintaining acceptable default risk levels.",
        "futuristic_view": "Continuous behavioral credit scoring using IoT and real-time open banking APIs.",
        "client_ready_details": "Batch scoring pipeline integration with loan origination system.",
        "keyword": "credit scoring"
    },
    {
        "domain": "Retail",
        "subdomain": "Customer Analytics",
        "use_case_name": "Customer Churn Prediction",
        "description": "Predicts which customers are likely to stop buying based on their purchase history and engagement metrics.",
        "ml_technique": "Random Forest / XGBoost",
        "input_data": "Purchase frequency, recency, demographics, web interactions",
        "value": "Increases customer retention by targeting at-risk users with tailored promotions.",
        "futuristic_view": "Hyper-personalized retention strategies using deep reinforcement learning.",
        "client_ready_details": "Automated weekly scoring pipeline triggering targeted email campaigns directly into CRM.",
        "keyword": "customer churn"
    },
    {
        "domain": "Retail",
        "subdomain": "Supply Chain",
        "use_case_name": "Demand Forecasting",
        "description": "Forecasts future product demand to optimize inventory levels and reduce stockouts.",
        "ml_technique": "ARIMA / Prophet / XGBoost",
        "input_data": "Historical sales, pricing, holidays, promotions, weather",
        "value": "Minimizes stockouts and overstock, optimizing supply chain costs.",
        "futuristic_view": "Fully automated, self-healing supply networks that place orders without human intervention.",
        "client_ready_details": "Daily forecast generation feeding directly into ERP systems.",
        "keyword": "demand forecasting"
    },
    {
        "domain": "Healthcare",
        "subdomain": "Clinical Operations",
        "use_case_name": "Patient Readmission Risk",
        "description": "Assesses a patient's likelihood to be readmitted within 30 days after discharge.",
        "ml_technique": "Logistic Regression / Random Forest",
        "input_data": "Patient EHR, lab results, demographic data, prior admission history",
        "value": "Lower readmission rates, improved patient outcomes, and reduced hospital penalties.",
        "futuristic_view": "Integration of wearable continuous health monitoring data post-discharge.",
        "client_ready_details": "Integrated directly into EHR systems (like Epic) to flag high-risk patients at discharge.",
        "keyword": "patient readmission"
    },
    {
        "domain": "Healthcare",
        "subdomain": "Diagnostics",
        "use_case_name": "Medical Image Classification",
        "description": "Identifies anomalies such as tumors or fractures from X-rays or MRI scans.",
        "ml_technique": "Support Vector Machines (traditional) / PCA + SVM",
        "input_data": "Extracted image features, pixel intensity statistics",
        "value": "Assists radiologists in prioritizing high-risk cases.",
        "futuristic_view": "Multimodal diagnostic assistants combining genomic, imaging, and clinical text.",
        "client_ready_details": "Deployed as a web-service integrated with PACS (Picture Archiving and Communication Systems).",
        "keyword": "medical imaging"
    },
    {
        "domain": "Manufacturing",
        "subdomain": "Operations",
        "use_case_name": "Predictive Maintenance",
        "description": "Monitors equipment sensors to predict when a machine is likely to fail.",
        "ml_technique": "Gradient Boosting Machines / Survival Analysis",
        "input_data": "Vibration, temperature, pressure sensor logs, historical failure data",
        "value": "Reduces unplanned downtime by 30% and saves maintenance costs.",
        "futuristic_view": "Digital twins of entire factory floors continuously updated with live telemetry.",
        "client_ready_details": "Edge-deployed models alerting floor managers via dashboard.",
        "keyword": "predictive maintenance"
    },
    {
        "domain": "Manufacturing",
        "subdomain": "Quality Control",
        "use_case_name": "Defect Detection",
        "description": "Automatically identifies defective parts on the assembly line using structural features.",
        "ml_technique": "One-class SVM / Random Forest",
        "input_data": "Sensor readings, dimensional measurements, weight",
        "value": "Reduces manual inspection time and minimizes defective products shipped.",
        "futuristic_view": "In-line real-time correction of manufacturing parameters to prevent defects before they occur.",
        "client_ready_details": "Real-time edge inference deployed on the production line with PLCs.",
        "keyword": "defect detection"
    },
    {
        "domain": "Transportation",
        "subdomain": "Logistics",
        "use_case_name": "Delivery Route Optimization",
        "description": "Optimizes driver routes dynamically based on traffic, delivery windows, and parcel loads.",
        "ml_technique": "Ant Colony Optimization / K-Means Clustering",
        "input_data": "Delivery addresses, traffic data, vehicle capacity",
        "value": "Cuts fuel consumption by 15% and increases on-time deliveries.",
        "futuristic_view": "Autonomous drone and truck swarm coordination.",
        "client_ready_details": "Cloud-based routing API integrated with driver mobile applications.",
        "keyword": "route optimization"
    },
    {
        "domain": "Energy",
        "subdomain": "Smart Grids",
        "use_case_name": "Energy Consumption Forecasting",
        "description": "Predicts future energy consumption to balance grid load and optimize generation.",
        "ml_technique": "SARIMA / SVR",
        "input_data": "Historical consumption, weather forecasts, time of day/year",
        "value": "Prevents grid overloads and reduces carbon footprint by optimizing power dispatch.",
        "futuristic_view": "Decentralized micro-grid trading platforms managed by intelligent agents.",
        "client_ready_details": "Hourly batch forecasts integrated into utility SCADA systems.",
        "keyword": "energy forecasting"
    },
    {
        "domain": "Energy",
        "subdomain": "Renewables",
        "use_case_name": "Wind Turbine Power Output Prediction",
        "description": "Predicts short-term power generation from wind turbines to bid effectively in energy markets.",
        "ml_technique": "Random Forest Regressor / KNN",
        "input_data": "Wind speed, wind direction, humidity, temperature",
        "value": "Maximizes revenue in spot markets by accurately committing power generation.",
        "futuristic_view": "Real-time pitch and yaw adjustments learned via reinforcement learning.",
        "client_ready_details": "Microservice API providing 15-minute ahead forecasts for trading desks.",
        "keyword": "wind power prediction"
    },
    {
        "domain": "Agriculture",
        "subdomain": "Precision Farming",
        "use_case_name": "Crop Yield Prediction",
        "description": "Estimates expected crop yield to optimize harvesting logistics and sales pricing.",
        "ml_technique": "Multiple Linear Regression / XGBoost",
        "input_data": "Soil moisture, historical weather, fertilization rates, satellite indices (NDVI)",
        "value": "Improves supply chain planning and maximizes farmer revenue.",
        "futuristic_view": "Automated drone fleets performing spot-treatment of crops based on micro-level yield projections.",
        "client_ready_details": "Dashboard for agricultural cooperatives providing field-level yield heatmaps.",
        "keyword": "crop yield"
    },
    {
        "domain": "Cybersecurity",
        "subdomain": "Network Security",
        "use_case_name": "Network Intrusion Detection",
        "description": "Identifies malicious activity or policy violations within a corporate network.",
        "ml_technique": "Isolation Forest / PCA anomaly detection",
        "input_data": "Network flow logs, packet sizes, protocol types, port numbers",
        "value": "Detects zero-day attacks and limits data breaches.",
        "futuristic_view": "Autonomous active defense systems that isolate compromised nodes in milliseconds.",
        "client_ready_details": "Integrated with SIEM (e.g., Splunk) generating high-fidelity alerts for SOC analysts.",
        "keyword": "intrusion detection"
    },
    {
        "domain": "Cybersecurity",
        "subdomain": "Endpoint Security",
        "use_case_name": "Malware Classification",
        "description": "Classifies executables as benign or malicious based on static analysis features.",
        "ml_technique": "Random Forest / Naive Bayes",
        "input_data": "PE header features, file entropy, imported DLLs",
        "value": "Provides rapid initial triage of suspected files before heavy dynamic analysis.",
        "futuristic_view": "Generative adversarial networks applied to preemptively mutate malware signatures for sandbox testing.",
        "client_ready_details": "Deployed as an API endpoint for an email gateway to scan attachments.",
        "keyword": "malware detection"
    },
    {
        "domain": "Human Resources",
        "subdomain": "Talent Acquisition",
        "use_case_name": "Resume Screening",
        "description": "Scores and ranks incoming resumes against a specific job description.",
        "ml_technique": "TF-IDF + Cosine Similarity / SVM",
        "input_data": "Resume text, job description text",
        "value": "Reduces time-to-hire and standardizes the screening process.",
        "futuristic_view": "Interactive AI evaluating candidate domain knowledge during live automated technical screens.",
        "client_ready_details": "Integrated directly into Applicant Tracking Systems (ATS) as a plugin.",
        "keyword": "resume screening"
    },
    {
        "domain": "Human Resources",
        "subdomain": "Employee Retention",
        "use_case_name": "Employee Attrition Prediction",
        "description": "Identifies employees at high risk of leaving the company.",
        "ml_technique": "Logistic Regression / Decision Trees",
        "input_data": "Tenure, salary, performance reviews, commute distance, recent promotions",
        "value": "Allows proactive retention efforts saving significant recruitment and training costs.",
        "futuristic_view": "Organizational network analysis mapping invisible social influences on attrition.",
        "client_ready_details": "Monthly batch job updating HR dashboards with anonymized risk stratifications.",
        "keyword": "employee attrition"
    },
    {
        "domain": "Marketing",
        "subdomain": "Customer Segmentation",
        "use_case_name": "Behavioral Segmentation",
        "description": "Groups customers into distinct profiles based on purchasing behavior for targeted campaigns.",
        "ml_technique": "K-Means Clustering / DBSCAN",
        "input_data": "RFM (Recency, Frequency, Monetary) metrics, product categories bought",
        "value": "Increases marketing ROI by ensuring the right message reaches the appropriate audience.",
        "futuristic_view": "Dynamic micro-segmentation updated continuously based on live clickstream data.",
        "client_ready_details": "Daily refreshed clusters pushed to marketing automation platforms like Marketo.",
        "keyword": "customer segmentation"
    },
    {
        "domain": "Marketing",
        "subdomain": "E-Commerce",
        "use_case_name": "Product Recommendation",
        "description": "Suggests relevant items to users based on their browsing and purchase history.",
        "ml_technique": "Collaborative Filtering / Association Rules (Apriori)",
        "input_data": "User purchase history, item metadata, user ratings",
        "value": "Drives cross-sell and up-sell, increasing average order value.",
        "futuristic_view": "Context-aware conversational commerce seamlessly integrating recommendations into chat.",
        "client_ready_details": "Low-latency REST API queried continuously during user session.",
        "keyword": "recommendation system"
    },
    {
        "domain": "Telecommunications",
        "subdomain": "Network Operations",
        "use_case_name": "Cell Tower Failure Prediction",
        "description": "Predicts impending degradations in cell tower performance.",
        "ml_technique": "Gradient Boosting",
        "input_data": "Signal strength logs, weather conditions, power supply metrics",
        "value": "Ensures uninterrupted service and reduces costly emergency truck rolls.",
        "futuristic_view": "Self-healing networks that automatically reroute capacity around failing hardware.",
        "client_ready_details": "Alerting system integrated into Network Operations Center (NOC).",
        "keyword": "tower failure"
    },
    {
        "domain": "Real Estate",
        "subdomain": "Valuation",
        "use_case_name": "Automated Property Valuation",
        "description": "Estimates market value of a property based on its characteristics and recent comps.",
        "ml_technique": "XGBoost Regressor / ElasticNet",
        "input_data": "Square footage, location, number of bedrooms, recent nearby sales",
        "value": "Accelerates mortgage approvals and assists real estate investors in screening deals.",
        "futuristic_view": "Valuation models integrating massive 3D urban simulations and micro-climate impacts.",
        "client_ready_details": "On-demand valuation API for property management portals.",
        "keyword": "property valuation"
    }
]
